### PR TITLE
Setup authentication using oneauth

### LINKED ISSUE #2: Setup authentication using oneauth
Currently, the project uses Django authentication mechanism but we need to authenticate users via our SSO platform [oneauth](https://account.codingblocks.com) 

To get started with this task:
1. I'll recommend you to read about the authentication flow in OAuth 2.0. You refer [this](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2) article.
2. Go to https://account.codingblocks.com and create a new Client under My Clients tab
    - Use localhost:8000 as the callback url and default url
3.  Create two vars in `settings.py` file `ONEAUTH_CLIENT_ID` and `ONEAUTH_CLIENT_SECRET` whose values are fetched from the .env file

ToDos for the task are:
- [ ] Replace `LOGIN_URL` in the `settings.py` with the authorization URL of oneauth
- [ ] Create a new application named `oneauth` and an endpoint which handles the callback from oneauth
- [ ] Exchange grant code with the access token
- [ ] Use access token to retrieve the user detail from the oneauth using `/api/users/me` endpoint
- [ ] Upsert user from the database
    - Use email id to fetch the user from database
        - [ ] If user exists update the user details and log in the user
        - [ ] If user doesn't extsts create the user and log in

### PR DESCRIPTION
**Pull request by prateek2211**
fix #2 
*  [X] Replace LOGIN_URL in the settings.py with the authorization URL of oneauth
* [X] Create a new application named oneauth and an endpoint which handles the callback from oneauth
* [X] Exchange grant code with the access token
* [X] Use access token to retrieve the user detail from the oneauth using /api/users/me endpoint
* [x] Upsert user from the database
 * Use email id to fetch the user from database
   * [x] If user exists update the user details and log in the user
   * [x] If user doesn't extsts create the user and log in

### CODE REVIEW

**Comment by prateek2211** [comment]
@jatinkatyal13  This pr adds support for authentication using oneauth.(It is a work in progress, almost done)
Currently, the user info obtained from endpoint after auth is returned as a response.

In order to add user data into the database, I had few questions:
* What user model are we going to user(django's in built or customized)
* What information in the return response from "https://account.codingblocks.com/api/users/me" is useful. (What need to be saved in db)
* After user info is saved into the db and we log in the user (using cookies), where should the user be directed?
* What is the main page shown to the user(which would require user to be logged-in)

Also, could you please review the work done until now

**Comment by prateek2211** [comment]
btw, callback url is `localhost:8000/callback/`

**Comment by jatinkatyal13** [comment]
@prateek2211 Awesome work until now!

As far as your questions go 
1. We will be using built-in Django user model. If in future we want to extend we can use the Profile schema
2. We need to populate following information
    - First Name
    - Last Name
    - Verified Email ( if not present use Email )
    - Role (if admin give the staff role in django else user role) (Only add this role while creating the user and not while updating. We may want to have admin on poker and not admin on oneauth)
3. After login we need to redirect them to the admin page. Because this is a very basic application we can make use of Django's admin panel to perform all our actions
    - If the user is not admin, land him on an error page `/error` saying that you need to be an administrator to use the application, although Django handles this scenario as well
4. For login let's stick with Django's login page and configure it to use our way of logging in. If it seems cumbersome we can have the following user story:
    - Index page explaining the application and a login link on the top right hand corner just like in https://cb.lk
    - Post login redirect to admin
    - If User is not allowed redirect too /error page

**Comment by prateek2211** [comment]
The built-in Django user model uses username to identify the users uniquely. I have used username here to identify the users.
If unique email constraint is necessary, then please tell, I will extend the AbstractUser.

**Comment by jatinkatyal13** [comment]
@prateek2211 Yes, the unique email constraint will be necessary. Other than that, the PR is perfect.

**Comment by prateek2211** [comment]
@jatinkatyal13 Done!

**Review by jatinkatyal13 — APPROVED** [review]

**Comment by jatinkatyal13** [comment]
LGTM 🚀 ! Format using 2 spaces and resolve the conflicts.

**Comment by jatinkatyal13** [comment]
@prateek2211 nice job! In future whenever you want to resolve merge conflict you can just back merge your branch with master using

```
git checkout <your branch>
git merge master
```

**Comment by prateek2211** [comment]
ok, I just had a habit of rebase, to avoid unnecessary merge commit 😅

**Pull request merged**
